/**
 * Terms of Use and Privacy Policy.
 *
 * The prose here is copied **verbatim** from the app's own legal screens
 * (`src/features/settings/LegalScreens.tsx` in the travel-companion repo). It is
 * deliberately not reworded: the web page and the in-app screen are the same
 * document, and a marketing site that softens its own terms is worse than
 * having none.
 *
 * When you edit the app's legal screens, edit this file to match.
 */

export interface LegalSection {
  heading: string;
  body: string;
}

export interface LegalDocument {
  slug: string;
  title: string;
  /** One line under the title, explaining what the reader is looking at. */
  standfirst: string;
  sections: LegalSection[];
}

/** Shown on both documents. The app says "this build"; a website needs a date. */
export const LEGAL_LAST_UPDATED = '[last updated — 8 August 2026]';

export const TERMS: LegalDocument = {
  slug: 'terms',
  title: 'Terms of Use',
  standfirst:
    'The same terms you are shown inside the app, under Settings → Legal. Reproduced here so you can read them before installing rather than after.',
  sections: [
    {
      heading: 'An account is required',
      body: "Roamlet requires a free account (email and password) to use any feature of the app. Your account is how we apply your daily cloud AI credit limit, keep your saved cities and plans tied to you, and prevent abuse of the shared cloud AI service. You're responsible for keeping your password confidential and for all activity under your account.",
    },
    {
      heading: 'Acceptable use',
      body: "Use Roamlet for personal travel planning and reference. Don't attempt to circumvent the daily cloud AI credit limit, extract or resell the on-device AI models, scrape or bulk-download city pack content, or use the app in any way that disrupts the service for other travellers.",
    },
    {
      heading: 'AI-generated content is not guaranteed to be correct',
      body: 'Answers — whether generated by the on-device AI model or the cloud fallback — are produced by a language model and can be incomplete, out of date, or simply wrong. Always verify anything safety-critical yourself before relying on it: emergency phone numbers, medical information, border and visa requirements, transit schedules, and similar time-sensitive or high-stakes facts. Roamlet is a travel companion, not an authority.',
    },
    {
      heading: 'No liability for travel decisions',
      body: 'Roamlet and its developer are not liable for any loss, expense, missed connection, medical issue, or other consequence arising from decisions made using information from the app, including AI-generated answers, offline maps, or city pack content. You are responsible for your own travel decisions and for verifying critical information through official sources.',
    },
    {
      heading: 'Downloaded models and storage',
      body: "On-device AI models are large files (hundreds of megabytes to a few gigabytes) that you choose to download to your device. You're responsible for having enough free storage and for any data charges if you download over a cellular connection — Roamlet always asks before starting a download on cellular data. Deleting a model frees its storage; you can re-download it later if you have a connection.",
    },
    {
      heading: 'Daily cloud AI credit policy',
      body: "If you haven't downloaded a local model but are online, Roamlet can answer questions using a cloud AI service instead. This is limited to 20 questions per rolling 24-hour period per account, tracked against your account, to keep the shared service sustainable and free. Downloading a local model removes this limit entirely and keeps your questions fully on-device.",
    },
    {
      heading: 'Account termination',
      body: "You may delete your account at any time from Settings → Account, which permanently removes your profile and cloud usage history. We may suspend or terminate an account that abuses the cloud AI service or otherwise violates these terms. Deleting your account does not remove content you've already downloaded to your own device.",
    },
  ],
};

export const PRIVACY: LegalDocument = {
  slug: 'privacy',
  title: 'Privacy Policy',
  standfirst:
    'The same policy you are shown inside the app, under Settings → Legal. The short version: when you use a downloaded model, nothing you ask ever reaches us.',
  sections: [
    {
      heading: 'What we collect',
      body: 'Your full name, phone number and email address, collected when you create an account. We also keep basic usage metadata needed to run the service: when you last signed in, whether a local AI model is downloaded, and your daily cloud AI question count. We do not collect location history, browsing history, or contacts.',
    },
    {
      heading: "What we don't collect",
      body: 'When you use the on-device AI (a downloaded local model), your questions and the answers you receive are processed entirely on your phone and are never sent to us or anyone else. We have no record of what you asked or what the model said. Your saved places, itineraries, and phrasebook activity also stay on your device.',
    },
    {
      heading: 'When data leaves your device',
      body: "Only two situations send anything off your phone: (1) authentication and account data (name, phone, email) go to Firebase to create and maintain your account, and (2) if you haven't downloaded a local model and choose to use the cloud AI fallback, your question and the app's answer pass through the third-party AI provider configured for the fallback service in order to generate a response. Neither of these happens for on-device AI use.",
    },
    {
      heading: 'Third-party services',
      body: 'Roamlet uses Firebase (Google) for account authentication and to store your profile and usage data, and — only when the cloud AI fallback is active — a third-party AI provider to generate answers. Each of these services processes the minimum data needed to do its job and is bound by its own privacy terms.',
    },
    {
      heading: 'Data retention',
      body: "Your account data is kept for as long as your account exists. Daily cloud AI question counts reset on a rolling 24-hour basis and aren't kept as a long-term history beyond what's needed to enforce the daily limit.",
    },
    {
      heading: 'Deleting your account and your data',
      body: "You can delete your account at any time from Settings → Account → Delete account. This permanently removes your profile and usage data from our systems. City packs and AI models you've downloaded live on your device's storage and are removed by deleting the app or clearing its storage — deleting your account does not reach into your device's local files.",
    },
    {
      heading: 'Your rights',
      body: 'You can request a copy of your account data or ask us to delete it by using the in-app deletion flow, or by contacting us through the support channel listed on the app’s store page. You can also stop using the cloud AI fallback entirely at any time by downloading a local model instead.',
    },
  ],
};

export const LEGAL_DOCUMENTS = [TERMS, PRIVACY];
